//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medDatabase.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int PatientId { get; set; }
        public int HouseNumber { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public int Patient_Id { get; set; }
        public string Street { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
