//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medDatabase.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistory
    {
        public int PatientId { get; set; }
        public int IllnessId { get; set; }
        public System.DateTime DiagnosisDate { get; set; }
        public System.DateTime LastVisitDate { get; set; }
    
        public virtual Illness Illness { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
