//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int EmployeeId { get; set; }
        public int DoctorSpecialtyId { get; set; }
        public int Employee_Id { get; set; }
    
        public virtual DoctorSpecialty DoctorSpecialty { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
